/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_corto_MainActivity */

#ifndef _Included_com_example_corto_MainActivity
#define _Included_com_example_corto_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_corto_MainActivity_PERMISSION_REQUEST_CODE
#define com_example_corto_MainActivity_PERMISSION_REQUEST_CODE 100L
#ifdef __cplusplus
}
#endif
#endif
